### ISSUE TITLE
AEM Event Proxy Package Updates

### ISSUE THREAD

**Issue by sarahxxu** [adobeio/adobeio-documentation#3]
Let's post here the latest packages updates

**Comment by sarahxxu** [comment]
[aem-event-proxy-0.36.226.zip](https://github.com/adobeio/adobeio-documentation/files/1723221/aem-event-proxy-0.36.226.zip)

**Comment by francoisledroff** [comment]
here is the latest package build compatible with `AEM 6.2` and `AEM 6.3`
[aem-event-proxy-6.3.4.zip](https://github.com/adobeio/adobeio-documentation/files/2026609/aem-event-proxy-6.3.4.zip)

**Comment by francoisledroff** [comment]
here is the latest package build compatible with `AEM 6.4` 
[aem-event-proxy-6.4.238.zip](https://github.com/adobeio/adobeio-documentation/files/2026673/aem-event-proxy-6.4.238.zip)
