### ISSUE TITLE
No event is triggered at provided webhook for CC assets

### ISSUE THREAD

**Issue by nisingla** [adobeio/adobeio-documentation#6]
Followed the steps mentioned in the documentation here https://github.com/adobeio/adobeio-documentation/blob/master/events/Webhook_docs_intro.md for receiving the events related to CC assets and webhook was verified successfully. But when uploading or deleting the asset on assets.adobe.com no event is triggered related to my AdobeID on the provided webhook. So is there anything needs to be done apart from steps mentioned in this documentation? I am using the same account for https://console.adobe.io for creating the new integration and also for https://assets.adobe.com.

**Comment by sarahxxu** [comment]
Hi @nisingla 
The reason why you didn't see any notifications is that you would also need to give an approval for your integration (or app in CC developer world) to your personal account. 

Here's what you would need to do:
1. Add Creative SDK as a service for your integration on Adobe I/O Console
1. Authenticate your integration with your Adobe account (you have a few options as listed below)
      - plug in your client id and hit this url -> https://ims-na1.adobelogin.com/ims/authorize/v1?response_type=code&client_id=<client-id-from-console>&scope=AdobeID%2Copenid%2Ccreative_sdk
      - use an auth playground application that we've created to authenticate: https://github.com/adobeio/Adobe-IMS-OAuth-Playground
1. Now you should be able to see your integration registered as an app on your account
      - Go to https://accounts.adobe.com
      - Click "Security & Privacy"
      - Scroll down to "Connected Applications"
      - Click "Manage" and you should be able to see it showing up

Note that if you authenticate directly by hitting the url, your integration will only be valid for 24 hrs. Afterwards, the integration expires and you would need to re-authentication. If you are building an application based on creative cloud events, you should use the renew token to renew your authentication.

Hope this helps and please feel free to reach out to me should you have any other questions/issues working with Adobe I/O!

- Sarah
